projects:
  awsreactnoteswalkthrAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: tpz72rqnsjbmtoubxvn6x7rqra
      endpoints:
        prod: >-
          https://ax4p6m463nfthamf6sel5eokoq.appsync-api.eu-west-1.amazonaws.com/graphql
